### ISSUE TITLE
resnet14b_w4 Needs training

### ISSUE THREAD

**Issue by kwierman** [drinkingkazu/ArchitecturePaperStudy#3]
https://github.com/drinkingkazu/ArchitecturePaperStudy/blob/master/EpochAnalysisImages/resnet14b_w4.png
![image](https://cloud.githubusercontent.com/assets/1746808/22836124/c3c4a056-ef80-11e6-8664-fb403f71be70.png)

**Comment by kwierman** [comment]
/home/kwierman/proj/src/caffe/build/tools/caffe train -solver=drinkingkazu_sp_resnet14b_w4_solver.prototxt -snapshot=sp_resnet14b_w4_iter_199250.caffemodel.h5 -gpu=3>log.txt
 

atm, I don't have permissions to /data/drinkingkazu/SPClassification/resnet14b_w4. I'll hop on this one later.

**Comment by drinkingkazu** [comment]
chmod done. Can you try again? (I did to that dir but also done anyway /data/drinkingkazu/SPClassification w/ -R).

Please make sure log.txt is cleaned up to the snap shot you intend to use.
Also, I think it would be good to be on the same page for slashing the learning rate.
Would you set it to 0.00006 (1/5 of currently used value)?

**Comment by drinkingkazu** [comment]
14b is now running @ Michigan, let's see if 14b_w4 is needed!
